# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'srhopkins'
tagline:          'whoami'
description:      'I love solving problems; continuously tweaking my solutions for conciseness, functionality, and that cool factor.'
url:              http://srhopkins.com
baseurl:          /

author:
  name:           'Steven Hopkins'
  url:            https://twitter.com/whoamisrhopkins

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/srhopkins
